site_name: Mon Blog

site_description: Economie, Afrique, Recherche et Développement
site_author: bduv

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.instant
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

nav:

  - Accueil: index.md

  - Articles:
      - articles/index.md

  - Podcasts:
      - podcasts/index.md

  - Vidéos:
      - videos/index.md

  - Afrique:
      - afrique/index.md

  - Développement économique:
      - developpement/index.md

  - Économie islamique:
      - economie-islamique/index.md

  - Agriculture:
      - agriculture/index.md

  - Fiscalité:
      - fiscalite/index.md

  - Économétrie:
      - econometrie/index.md

  - Politiques publiques:
      - politiques-publiques/index.md

  - Histoire:
      - histoire/index.md

  - Anthropologie:
      - anthropologie/index.md

  - Recherche:
      - recherche/index.md

  - Ressources pédagogiques:
      - ressources/index.md

  - Livres:
      - livres/index.md

  - Réflexions:
      - reflexions/index.md

  - À propos:
      - a-propos.md
